/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wireworld;

import java.awt.event.ActionListener;
import java.text.NumberFormat;
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author james8
 */
public class Gui extends javax.swing.JFrame {

    JFileChooser fileopen = new JFileChooser();
    FileFilter filter = new FileNameExtensionFilter("txt files", "txt");

    /**
     * Creates new form graphics
     */
    public Gui() {
        SimulationPanel simPanel = new SimulationPanel();
        initComponents();
    }

    public Gui(SimulationPanel simPanel) {
        jScrollPane5 = new JScrollPane(simPanel);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameNew = new javax.swing.JFrame();
        NumberFormat f = NumberFormat.getNumberInstance();
        f.setMaximumIntegerDigits(4);
        inpColls = new javax.swing.JFormattedTextField(f);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inpRows = new javax.swing.JFormattedTextField(f);
        btnFrameNewCreate = new javax.swing.JButton();
        btnFrameNewCancel = new javax.swing.JButton();
        frameOptions = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        checkProduceScreenshots = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnOptionsApply = new javax.swing.JButton();
        btnOptionsCancel = new javax.swing.JButton();
        btnOptionsSetDefaults = new javax.swing.JButton();
        btnOptionsDefaultImageInterval = new javax.swing.JButton();
        btnOptionsDefaultProduceScreenshots = new javax.swing.JButton();
        btnOptionsDefaultAnimationInterval = new javax.swing.JButton();
        inpOptionsImageInterval = new javax.swing.JFormattedTextField();
        inpOptionsAnimationInterval = new javax.swing.JFormattedTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        dlgFinish = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        btnDlgFinishYes = new javax.swing.JButton();
        btnDlgFinishNo = new javax.swing.JButton();
        frameHowTo = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        frameAbout = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnOptions = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnStart = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSlower = new javax.swing.JButton();
        btnFaster = new javax.swing.JButton();
        comboBoxItem = new javax.swing.JComboBox();
        //jScrollPane5 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuLoad = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuQuit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCheckProdImg = new javax.swing.JCheckBoxMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        manuPreferences = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuStart = new javax.swing.JMenuItem();
        menuPause = new javax.swing.JMenuItem();
        menuFinish = new javax.swing.JMenuItem();
        menuSlower = new javax.swing.JMenuItem();
        menuFaster = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuHowTo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuAbout = new javax.swing.JMenuItem();

        frameNew.setTitle("New");
        frameNew.setMinimumSize(new java.awt.Dimension(291, 86));
        frameNew.setName("frameNew"); // NOI18N
        frameNew.setResizable(false);
        frameNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                frameNewKeyPressed(evt);
            }
        });

        inpColls.setMaximumSize(new java.awt.Dimension(10, 27));
        inpColls.setName(""); // NOI18N
        inpColls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCollsActionPerformed(evt);
            }
        });

        jLabel6.setText("Colls");

        jLabel7.setText("Rows");

        btnFrameNewCreate.setText("Create");
        btnFrameNewCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameNewCreateActionPerformed(evt);
            }
        });

        btnFrameNewCancel.setText("Cancel");
        btnFrameNewCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameNewCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameNewLayout = new javax.swing.GroupLayout(frameNew.getContentPane());
        frameNew.getContentPane().setLayout(frameNewLayout);
        frameNewLayout.setHorizontalGroup(
            frameNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameNewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFrameNewCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFrameNewCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(frameNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(inpColls, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpRows, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameNewLayout.setVerticalGroup(
            frameNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameNewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inpColls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(inpRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrameNewCreate)
                    .addComponent(btnFrameNewCancel))
                .addContainerGap())
        );

        frameOptions.setTitle("Options");
        frameOptions.setResizable(false);

        jLabel2.setText("Image interval");

        checkProduceScreenshots.setSelected(true);
        checkProduceScreenshots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkProduceScreenshotsActionPerformed(evt);
            }
        });

        jLabel4.setText("Produce screenshots");

        jLabel5.setText("Animations interval (100ms)");

        btnOptionsApply.setText("Apply");
        btnOptionsApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsApplyActionPerformed(evt);
            }
        });

        btnOptionsCancel.setText("Cancel");
        btnOptionsCancel.setToolTipText("");
        btnOptionsCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsCancelActionPerformed(evt);
            }
        });

        btnOptionsSetDefaults.setText("Set Defaults");
        btnOptionsSetDefaults.setToolTipText("");
        btnOptionsSetDefaults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsSetDefaultsActionPerformed(evt);
            }
        });

        btnOptionsDefaultImageInterval.setText("Default");
        btnOptionsDefaultImageInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsDefaultImageIntervalActionPerformed(evt);
            }
        });

        btnOptionsDefaultProduceScreenshots.setText("Default");
        btnOptionsDefaultProduceScreenshots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsDefaultProduceScreenshotsActionPerformed(evt);
            }
        });

        btnOptionsDefaultAnimationInterval.setText("Default");
        btnOptionsDefaultAnimationInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsDefaultAnimationIntervalActionPerformed(evt);
            }
        });

        inpOptionsImageInterval.setText("1");
        inpOptionsImageInterval.setToolTipText("Number of simulations between taking screenshots");
        inpOptionsImageInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpOptionsImageIntervalActionPerformed(evt);
            }
        });

        inpOptionsAnimationInterval.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        inpOptionsAnimationInterval.setText("2");
        inpOptionsAnimationInterval.setToolTipText("Time between simulations *100 in ms");
        inpOptionsAnimationInterval.setMaximumSize(new java.awt.Dimension(10, 27));
        inpOptionsAnimationInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpOptionsAnimationIntervalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameOptionsLayout = new javax.swing.GroupLayout(frameOptions.getContentPane());
        frameOptions.getContentPane().setLayout(frameOptionsLayout);
        frameOptionsLayout.setHorizontalGroup(
            frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameOptionsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpOptionsAnimationInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOptionsDefaultAnimationInterval))
                    .addGroup(frameOptionsLayout.createSequentialGroup()
                        .addComponent(btnOptionsSetDefaults, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnOptionsCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOptionsApply, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(frameOptionsLayout.createSequentialGroup()
                            .addGap(486, 486, 486)
                            .addComponent(jSeparator6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator7))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frameOptionsLayout.createSequentialGroup()
                            .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(61, 61, 61)
                            .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inpOptionsImageInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkProduceScreenshots))
                            .addGap(18, 18, 18)
                            .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnOptionsDefaultProduceScreenshots)
                                .addComponent(btnOptionsDefaultImageInterval))))))
        );
        frameOptionsLayout.setVerticalGroup(
            frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameOptionsLayout.createSequentialGroup()
                .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(frameOptionsLayout.createSequentialGroup()
                                .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkProduceScreenshots)
                                    .addComponent(btnOptionsDefaultProduceScreenshots))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inpOptionsImageInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(btnOptionsDefaultImageInterval))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inpOptionsAnimationInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(btnOptionsDefaultAnimationInterval))))
                        .addGap(34, 49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameOptionsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOptionsSetDefaults)
                            .addComponent(btnOptionsCancel)
                            .addComponent(btnOptionsApply))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(frameOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel8.setText("Do you really want to finish the simulation?");

        btnDlgFinishYes.setText("Yes");

        btnDlgFinishNo.setText("No");

        javax.swing.GroupLayout dlgFinishLayout = new javax.swing.GroupLayout(dlgFinish.getContentPane());
        dlgFinish.getContentPane().setLayout(dlgFinishLayout);
        dlgFinishLayout.setHorizontalGroup(
            dlgFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgFinishLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(46, 46, 46))
            .addGroup(dlgFinishLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnDlgFinishYes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnDlgFinishNo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgFinishLayout.setVerticalGroup(
            dlgFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgFinishLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(dlgFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlgFinishYes)
                    .addComponent(btnDlgFinishNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameHowTo.setTitle("HowTo");
        frameHowTo.setResizable(false);

        jLabel11.setText("<html> In order to create new generation click <i>New</i> button<br> and put in the dimensions. Next you can start drawing<br> using your mouse and switch between <font color=\"yellow\">Conductor</font>,<br> <font color=\"red\">Electron  head</font> and <font color=\"blue\">Electron tail</font> in top right corner.<br><br>  Click <i>Start</i> to begin the simulation and <i>Pause</i><br> to pause it. When you click <i>Finish</i> you will be asked to<br> save state of last simulation to a file.<br>  You can <i>Load</i> and <i>Save</i> simulations using buttons<br> on the left of the interface. <html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Create", jPanel1);

        jLabel12.setText("<html> Options can be accessed either by click a button on<br> the right side of the interface or from <i>Preferences</i><br> in <i>Options</i> menu at the top of the aplication.<br><br>  Editing options works also in real-time - it means you<br> can change the options during the simulation.<br> </html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Options", jPanel2);

        jLabel13.setText("<html> Drawing can be done both by clicking <i>Left Mouse Button</i><br> or <u>keeping it pressed</u> and <u>moving mouse</u>.<br> To remove a field click <i>Right Mouse Button</i>.<br> You can change item type in the box in the top right<br> corner. </html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Drawing", jPanel3);

        jLabel1.setText("<html> Supported gates:<br> <ul> <li>Diode</li> <li>AND</li> <li>OR</li> <li>XOR/EOR</li> <li>NOT</li> <li>ANDNOT</li> <li>Flip</li> </ul> </html>");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gates", jPanel4);

        jLabel14.setText("<html> Aplication can load files in 2 ways of encoding,<br> which can be mixed, examples:<br> <table> <tr> <td> <ul> <li>Diode 0 3 Normal</li> <li>Diode 0 9 Reversed</li> <li>ElectronHead 1 3</li> </ul> </td> <td> <ul> <li>1 1 2</li> <li>1 2 1</li> <li>1 3 1</li> </ul> </td> </tr> <tr> <td> First item is name of element, then are the coordinates, last one is not obligatory, can be used only with some items. </td> <td> There firt two items are coordinates and the last one is the value of the field(0-3). </td> </tr> </table> </html>");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Files", jPanel5);

        javax.swing.GroupLayout frameHowToLayout = new javax.swing.GroupLayout(frameHowTo.getContentPane());
        frameHowTo.getContentPane().setLayout(frameHowToLayout);
        frameHowToLayout.setHorizontalGroup(
            frameHowToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        frameHowToLayout.setVerticalGroup(
            frameHowToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        frameAbout.setResizable(false);

        jLabel3.setText("WireWorld");

        jLabel9.setText("<html> <b>Wireworld</b> is a cellular automaton first<br> proposed by <i>Brian Silverman</i> in 1987,<br> as part of his program Phantom Fish Tank. <html>");

        jLabel10.setText("<html> Project planned and prepared by <br> <b>Jan Salowski</b>, Politechnika Warszawska <html>");

        javax.swing.GroupLayout frameAboutLayout = new javax.swing.GroupLayout(frameAbout.getContentPane());
        frameAbout.getContentPane().setLayout(frameAboutLayout);
        frameAboutLayout.setHorizontalGroup(
            frameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameAboutLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(frameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        frameAboutLayout.setVerticalGroup(
            frameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wireworld");
        setResizable(false);

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnOptions.setText("Options");
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnPause.setText("Pause");

        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSlower.setText("Slower");

        btnFaster.setText("Faster");

        comboBoxItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Conductor", "Electron Head", "Electron Tail", "OR", "XOR", "EOR", "NOT", "ANDNOT", "Flip" }));
        comboBoxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxItemActionPerformed(evt);
            }
        });

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jMenu2.setText("File");

        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        jMenu2.add(menuNew);

        menuLoad.setText("Load");
        jMenu2.add(menuLoad);

        menuSave.setText("Save");
        jMenu2.add(menuSave);

        menuQuit.setText("Quit");
        jMenu2.add(menuQuit);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Options");

        menuCheckProdImg.setSelected(true);
        menuCheckProdImg.setText("Produce Images");
        menuCheckProdImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCheckProdImgActionPerformed(evt);
            }
        });
        jMenu3.add(menuCheckProdImg);
        jMenu3.add(jSeparator3);

        manuPreferences.setText("Preferences");
        manuPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuPreferencesActionPerformed(evt);
            }
        });
        jMenu3.add(manuPreferences);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Actions");

        menuStart.setText("Start");
        jMenu1.add(menuStart);

        menuPause.setText("Pause");
        jMenu1.add(menuPause);

        menuFinish.setText("Finish");
        jMenu1.add(menuFinish);

        menuSlower.setText("Slower");
        jMenu1.add(menuSlower);

        menuFaster.setText("Faster");
        jMenu1.add(menuFaster);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Help");

        menuHowTo.setText("How To");
        menuHowTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHowToActionPerformed(evt);
            }
        });
        jMenu4.add(menuHowTo);
        jMenu4.add(jSeparator4);

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu4.add(menuAbout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSlower, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFaster, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboBoxItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOptions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFaster)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSlower)
                        .addComponent(btnStart)
                        .addComponent(btnPause)
                        .addComponent(btnFinish)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsActionPerformed
        frameOptions.setSize(360, 160);
        frameOptions.pack();
        frameOptions.setLocationRelativeTo(null);
        frameOptions.setVisible(true);
    }//GEN-LAST:event_btnOptionsActionPerformed

    private void manuPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuPreferencesActionPerformed
        frameOptions.setSize(360, 160);
        frameOptions.pack();
        frameOptions.setLocationRelativeTo(null);
        frameOptions.setVisible(true);
    }//GEN-LAST:event_manuPreferencesActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed


    }//GEN-LAST:event_btnLoadActionPerformed

    private void inpOptionsAnimationIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpOptionsAnimationIntervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpOptionsAnimationIntervalActionPerformed

    private void inpOptionsImageIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpOptionsImageIntervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpOptionsImageIntervalActionPerformed

    private void btnOptionsCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsCancelActionPerformed
        frameOptions.dispose();
    }//GEN-LAST:event_btnOptionsCancelActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        //frameNew.setSize(291, 110);
        frameNew.pack();
        frameNew.setLocationRelativeTo(null);
        frameNew.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnFrameNewCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameNewCancelActionPerformed
        frameNew.dispose();
    }//GEN-LAST:event_btnFrameNewCancelActionPerformed

    private void frameNewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frameNewKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            frameOptions.dispose();
        }
    }//GEN-LAST:event_frameNewKeyPressed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    private void inpCollsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCollsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCollsActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinishActionPerformed

    private void comboBoxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxItemActionPerformed

    private void btnOptionsDefaultImageIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsDefaultImageIntervalActionPerformed
        inpOptionsImageInterval.setText("1");
    }//GEN-LAST:event_btnOptionsDefaultImageIntervalActionPerformed

    private void btnOptionsDefaultAnimationIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsDefaultAnimationIntervalActionPerformed
        inpOptionsAnimationInterval.setText("2");
    }//GEN-LAST:event_btnOptionsDefaultAnimationIntervalActionPerformed

    private void checkProduceScreenshotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkProduceScreenshotsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkProduceScreenshotsActionPerformed

    private void btnOptionsDefaultProduceScreenshotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsDefaultProduceScreenshotsActionPerformed
        checkProduceScreenshots.setSelected(true);
    }//GEN-LAST:event_btnOptionsDefaultProduceScreenshotsActionPerformed

    private void btnOptionsSetDefaultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsSetDefaultsActionPerformed
        checkProduceScreenshots.setSelected(true);
        inpOptionsAnimationInterval.setText("2");
        inpOptionsImageInterval.setText("1");
    }//GEN-LAST:event_btnOptionsSetDefaultsActionPerformed

    private void btnOptionsApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsApplyActionPerformed
        menuCheckProdImg.setSelected(checkProduceScreenshots.isSelected());
        frameOptions.dispose();
    }//GEN-LAST:event_btnOptionsApplyActionPerformed

    private void btnFrameNewCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameNewCreateActionPerformed
        frameNew.dispose();
    }//GEN-LAST:event_btnFrameNewCreateActionPerformed

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
        //frameNew.setSize(291, 110);
        frameNew.pack();
        frameNew.setLocationRelativeTo(null);
        frameNew.setVisible(true);
    }//GEN-LAST:event_menuNewActionPerformed

    private void menuHowToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHowToActionPerformed
        frameHowTo.pack();
        frameHowTo.setLocationRelativeTo(null);
        frameHowTo.setVisible(true);
    }//GEN-LAST:event_menuHowToActionPerformed

    private void menuCheckProdImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCheckProdImgActionPerformed

    }//GEN-LAST:event_menuCheckProdImgActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        frameAbout.pack();
        frameAbout.setLocationRelativeTo(null);
        frameAbout.setVisible(true);
    }//GEN-LAST:event_menuAboutActionPerformed

    void QuitListener(ActionListener listenForQuit) {
        btnQuit.addActionListener(listenForQuit);
        menuQuit.addActionListener(listenForQuit);
    }

    void addStartListener(ActionListener listenForStart) {
        btnStart.addActionListener(listenForStart);
        menuStart.addActionListener(listenForStart);
    }

    void addPauseListener(ActionListener listenForPause) {
        btnPause.addActionListener(listenForPause);
        menuPause.addActionListener(listenForPause);
    }

    void addFinishListener(ActionListener listenForFinish) {
        btnFinish.addActionListener(listenForFinish);
        menuFinish.addActionListener(listenForFinish);
    }

    void CreateNewListener(ActionListener listenbtnFrameNewCreate) {
        btnFrameNewCreate.addActionListener(listenbtnFrameNewCreate);
    }

    void LoadListener(ActionListener listenbtnLoad) {
        btnLoad.addActionListener(listenbtnLoad);
    }

    void SaveListener(ActionListener listenbtnSave) {
        btnSave.addActionListener(listenbtnSave);
    }

    void addSlowerListener(ActionListener listenForSlower) {
        btnSlower.addActionListener(listenForSlower);
        menuSlower.addActionListener(listenForSlower);
    }

    void addFasterListener(ActionListener listenForFaster) {
        btnFaster.addActionListener(listenForFaster);
        menuFaster.addActionListener(listenForFaster);
    }

    void ComboListener(ActionListener listencomboBoxItem) {
        comboBoxItem.addActionListener(listencomboBoxItem);
    }

    void OptionsApplyListener(ActionListener listenbtnOptionsApply) {
        btnOptionsApply.addActionListener(listenbtnOptionsApply);
    }

    void OptionsCheckProdImgListener(ActionListener listenmanuCheckProdImg) {
        if (checkProduceScreenshots.isSelected()) {
            checkProduceScreenshots.setSelected(false);
        } else {
            checkProduceScreenshots.setSelected(true);
        }
        menuCheckProdImg.addActionListener(listenmanuCheckProdImg);
    }

    public boolean checkProduceScreenshots() {
        return checkProduceScreenshots.isSelected();
    }

    public int getOptionsImageInterval() {
        return Integer.parseInt(inpOptionsImageInterval.getText());
    }

    public int getOptionsAnimationInterval() {
        return Integer.parseInt(inpOptionsAnimationInterval.getText());
    }

    public void setProduceScreenshots(boolean value) {
        checkProduceScreenshots.setSelected(value);
    }

    public void setOptionsImageInterval(String value) {
        inpOptionsImageInterval.setText(value);
    }

    public void setOptionsAnimationInterval(String value) {
        inpOptionsAnimationInterval.setText(value);
    }

    public int getColls() {
        return Integer.parseInt(inpColls.getText());
    }

    public int getRows() {
        return Integer.parseInt(inpRows.getText());
    }

    public String getCombo() {
        String value = "Conductor";
        switch (comboBoxItem.getSelectedItem().toString()) {
            case "Conductor":
                value = "Conductor";
                break;
            case "Electron Head":
                value = "ElectronHead";
                break;
            case "Electron Tail":
                value = "ElectronTail";
                break;
            case "OR":
                value = "OR";
                break;
            case "XOR":
                value = "XOR";
                break;
            case "EOR":
                value = "EOR";
                break;
            case "NOT":
                value = "NOT";
                break;
            case "ANDNOT":
                value = "ANDNOT";
                break;
            case "Flip":
                value = "Flip";
                break;
            default:

                break;
        }
        return value;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDlgFinishNo;
    private javax.swing.JButton btnDlgFinishYes;
    private javax.swing.JButton btnFaster;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnFrameNewCancel;
    private javax.swing.JButton btnFrameNewCreate;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnOptionsApply;
    private javax.swing.JButton btnOptionsCancel;
    private javax.swing.JButton btnOptionsDefaultAnimationInterval;
    private javax.swing.JButton btnOptionsDefaultImageInterval;
    private javax.swing.JButton btnOptionsDefaultProduceScreenshots;
    private javax.swing.JButton btnOptionsSetDefaults;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSlower;
    private javax.swing.JButton btnStart;
    private javax.swing.JCheckBox checkProduceScreenshots;
    private javax.swing.JComboBox comboBoxItem;
    private javax.swing.JDialog dlgFinish;
    private javax.swing.JFrame frameAbout;
    private javax.swing.JFrame frameHowTo;
    private javax.swing.JFrame frameNew;
    private javax.swing.JFrame frameOptions;
    private javax.swing.JFormattedTextField inpColls;
    private javax.swing.JFormattedTextField inpOptionsAnimationInterval;
    private javax.swing.JFormattedTextField inpOptionsImageInterval;
    private javax.swing.JFormattedTextField inpRows;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem manuPreferences;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JCheckBoxMenuItem menuCheckProdImg;
    private javax.swing.JMenuItem menuFaster;
    private javax.swing.JMenuItem menuFinish;
    private javax.swing.JMenuItem menuHowTo;
    private javax.swing.JMenuItem menuLoad;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuPause;
    private javax.swing.JMenuItem menuQuit;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSlower;
    private javax.swing.JMenuItem menuStart;
    // End of variables declaration//GEN-END:variables
}
